---
title: mugun_home
timezone: Asia/Hong_Kong
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: 来自辣鸡学校的辣鸡研究生，现在研究大数据方向，但实际上我觉得我本体还是在PHP上（滑稽）
keyword: mugun,cs.big data,php,java,hadoop,python,r
url: mugun.github.io
baseurl: 
nav:
  home: "/"
  tags: "/tags.html"
author: mugun
nickname: mugun
bio: 
avatar: 
search: true
nightMode: true
disqus: false
disqus_url: https://liaokeyu.disqus.com/embed.js
social-share: true
theme-color: default
postPatterns: circuitBoard
recommend-tags: true
recommend-condition-size: 12
paginate: 6
paginate_path: page:num
exclude:
- node_modules
- dev
- package.json
- gulpfile.js
- ".gitignore"
- README.md
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
RSS: false
gems:
- jekyll-paginate
